# Generated by Django 5.1.6 on 2025-05-05 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ilce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilce_adi', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori_adi', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sehir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sehir_adi', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Magaza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magaza_adi', models.CharField(max_length=100)),
                ('adres', models.TextField(blank=True, null=True)),
                ('telefon', models.CharField(blank=True, max_length=20, null=True)),
                ('ilce', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stok.ilce')),
                ('sehir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stok.sehir')),
            ],
            options={
                'unique_together': {('sehir', 'ilce', 'magaza_adi')},
            },
        ),
        migrations.AddField(
            model_name='ilce',
            name='sehir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ilceler', to='stok.sehir'),
        ),
        migrations.CreateModel(
            name='Urun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urun_adi', models.CharField(max_length=100)),
                ('barkod', models.CharField(max_length=50, unique=True)),
                ('fiyat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stok.kategori')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='ilce',
            unique_together={('sehir', 'ilce_adi')},
        ),
        migrations.CreateModel(
            name='Stok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adet', models.PositiveIntegerField(default=0)),
                ('son_guncelleme', models.DateTimeField(auto_now=True)),
                ('magaza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stok.magaza')),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stok.urun')),
            ],
            options={
                'unique_together': {('magaza', 'urun')},
            },
        ),
    ]
